### ISSUE TITLE
大佬，这个支持M1 的mac吗

### ISSUE THREAD

**Issue by lguiwind** [moyuwa/ApkCheckPack#10]
大佬，这个支持M1 的mac吗

**Comment by moyuwa** [comment]
没测试过，用的go自带的跨平台编译，M1估计不行

**Comment by 123456789zws** [comment]
请问，脱壳后的全部dex打包为apk，可以用它检测出那些反调试等的字符串吗

**Comment by moyuwa** [comment]
> 请问，脱壳后的全部dex打包为apk，可以用它检测出那些反调试等的字符串吗

可以的
