### ISSUE TITLE
请问提示无效路径是什么原因呢 win10

### ISSUE THREAD

**Issue by 123456789zws** [moyuwa/ApkCheckPack#11]
提示无效路径是什么原因呢 win10

**Comment by moyuwa** [comment]
apk文件路径问题，你换不带空格的英文路径，或将程序放到apk同目录下

**Comment by 123456789zws** [comment]
放在一起了，然后这是我运行的命令还是提示无效路径 C:\apk>ApkCheckPack.exe 1.apk

**Comment by moyuwa** [comment]
是不是文件、文件夹权限问题？

**Comment by moyuwa** [comment]
> 放在一起了，然后这是我运行的命令还是提示无效路径 C:\apk>ApkCheckPack.exe 1.apk

命令是 ApkCheckPack.exe -f 1.apk，新版本改成-f指定文件/文件夹了

**Comment by moyuwa** [comment]
> 放在一起了，然后这是我运行的命令还是提示无效路径 C:\apk>ApkCheckPack.exe 1.apk

命令是 ApkCheckPack.exe -f 1.apk，新版本改成-f指定文件/文件夹了

**Comment by 123456789zws** [comment]
可以了，感谢回复，工具挺不错的
