### ISSUE TITLE
是不是过一下root和模拟器检测挺麻烦的

### ISSUE THREAD

**Issue by ysn2382617094wsw** [moyuwa/ApkCheckPack#8]
C:\Users\ysn23\Desktop\jiagu>ApkCheckPack_windows_amd64.exe -s=true -f 1.apk
Verification scheme used: v2 版本签名,无Janus漏洞!
Cert 2152585871a664b0d6cf54c20b934b4e93eff399, valid from 2017-06-22T01:47:58Z to 2042-06-16T01:47:58Z, Subject: C=CN, ST=SC, L=CD, CN=youma, Issuer: C=CN, ST=SC, L=CD, CN=youma
发现加固特征 Soname  梆梆安全（定制版）->lib/arm64-v8a/libDexHelper.so
发现加固特征 Soname  梆梆安全（定制版）->lib/armeabi-v7a/libDexHelper.so
发现加固特征 Sopath  腾讯Bugly->lib/arm64-v8a/libBugly.so
发现加固特征 Soname  腾讯Bugly->lib/arm64-v8a/libBugly.so
发现加固特征 Soname  腾讯Bugly->lib/armeabi-v7a/libBugly.so
发现加固特征 Soname  梆梆安全（企业版）->lib/armeabi-v7a/libDexHelper-x86.so
发现加固特征 Soname  梆梆安全（企业版）->lib/arm64-v8a/libDexHelper-x86.so
发现加固特征 Soname  梆梆安全（企业版）->lib/armeabi-v7a/libDexHelper.so
发现加固特征 Soname  梆梆安全（企业版）->lib/arm64-v8a/libDexHelper.so
发现加固特征 Soregex 梆梆安全（企业版）->lib/armeabi-v7a/libDexHelper-x86.so
发现加固特征 Soregex 梆梆安全（企业版）->lib/arm64-v8a/libDexHelper-x86.so
发现ROOT检测特征   [dex]: /system/app/Kinguser.apk->classes.dex
发现模拟器检测特征 [dex]: test-keys->classes.dex
3210 / 3210 [------------------------------------------------------------------------------------------] 100.00% 72 p/s

**Comment by moyuwa** [comment]
工具只能识别有无加固检测，辅助人工分析，不是用于绕过的，需要绕过建议去研究frida hook
