### ISSUE TITLE
您好，可以加入开发框架的识别吗？

### ISSUE THREAD

**Issue by cloud-jie** [moyuwa/ApkCheckPack#9]
例如：http://mpaas.com/，https://flutter.cn/
使用上述开发框架的应用天然就存在一定的防护，不仅仅在代码处，还体现在抓包等方面，四舍五入也算加固
再者，从程序实现而言，也只需要添加特征即可，例如flutter特征为 lib 目录下的 libflutter.so 文件，如下：
![image](https://github.com/moyuwa/ApkCheckPack/assets/63632785/4a55d791-7965-4b2a-bc01-e7887c9bd27c)
综上所述，加入这个功能不是特别离谱的请求，并且从代码实现来看，也不偏离程序设计的初衷

**Comment by moyuwa** [comment]
好主意，这两个SDK的特征我后面加入，扫描开发框架功能主要缺特征库，需要大家反馈积累；
这两个开发框架其实和OPPO的安全开发SDK类似，都是通过已封装好的SDK去开发功能，比如现在常见的腾讯乐固组件开发登录、支付；

**Comment by moyuwa** [comment]
规则库 https://github.com/LibChecker/LibChecker-Rules

**Comment by moyuwa** [comment]
开发框架识别已加入
